-file("/usr/local/Cellar/erlang/23.3/lib/erlang/lib/parsetools-2.2/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("./lexer.xrl", 95).
-export([reserved_word/1, reserved_word2/1, diferenciador/3]).

%Definición del primer grupo de palabras reservadas (estos tendrán el mismo color)
reserved_word('if')-> true;
reserved_word('else')-> true;
reserved_word('for')-> true;
reserved_word('do')-> true;
reserved_word('printf')-> true;
reserved_word('scanf')-> true;
reserved_word('main')-> true;
reserved_word('break')-> true;
reserved_word('switch')-> true;
reserved_word('enum')-> true;
reserved_word('return')-> true;
reserved_word('sizeof')-> true;
reserved_word('typedef')-> true;
reserved_word('while')-> true;
reserved_word('goto')-> true;
reserved_word('continue')-> true;
reserved_word('struct')-> true;
reserved_word('union')-> true;
reserved_word(_)-> false.

%Definición del segundo grupo de palabras reservadas (estos tendrán otro color)
reserved_word2('int') ->true;
reserved_word2('char') ->true;
reserved_word2('True') ->true;
reserved_word2('true') ->true;
reserved_word2('False') ->true;
reserved_word2('false') ->true;
reserved_word2('unsigned') ->true;
reserved_word2('signed') ->true;
reserved_word2('short') ->true;
reserved_word2('long') ->true;
reserved_word2('float') ->true;
reserved_word2('double') ->true;
reserved_word2('void')-> true;
reserved_word2('auto')-> true;
reserved_word2('const')-> true;
reserved_word2('register')-> true;
reserved_word2('extern')-> true;
reserved_word2('enum')-> true;
reserved_word2('volatile')-> true;
reserved_word2(_)-> false.

%Función que determina si la palabra corresponde al segundo grupo de palabras reservadas o es un identificador
diferenciador(Atom, TokenChars, TokenLine)->
  case reserved_word2(Atom) of
      true -> {token, {'RW', "<span class=\"RW2\">" ++ TokenChars ++"</span>", TokenLine}};
      false -> {token,{'ID', "<span class=\"ID\">" ++ TokenChars ++"</span>", TokenLine}}
  end.

-file("/usr/local/Cellar/erlang/23.3/lib/erlang/lib/parsetools-2.2/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("./lexer.erl", 358).
yystate() -> 50.

yystate(53, [47|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 6, Tlen);
yystate(53, [42|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 6, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(51, [126|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [125|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [124|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [123|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [94|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [93|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [92|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [91|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [63|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [62|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [61|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [60|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [59|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [58|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [47|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [46|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [45|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [44|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [43|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [42|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [41|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [40|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [38|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [37|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [36|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [35|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [34|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [33|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [32|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [13|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [9|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(51, Ics, Line, Tlen+1, 41, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,51};
yystate(50, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line+1, Tlen+1, Action, Alen);
yystate(50, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 68 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 70, C =< 90 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 100 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 102, C =< 122 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, [124|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 39, Tlen);
yystate(49, [101|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 39, Tlen);
yystate(49, [69|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 39, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(49, Ics, Line, Tlen+1, 39, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {39,Tlen,Ics,Line,49};
yystate(48, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(47, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line+1, Tlen+1, Action, Alen);
yystate(47, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(45, [45|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 38, Tlen);
yystate(45, [43|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 38, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, 38, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(43, [126|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [125|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [124|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [123|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [94|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [93|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [92|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [91|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [63|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [62|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [60|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [59|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [58|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [47|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [46|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [45|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [44|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [43|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [42|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [41|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [40|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [38|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [37|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [36|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [35|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [34|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [33|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [32|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [13|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [10|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line+1, Tlen+1, 42, Tlen);
yystate(43, [9|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(39, Ics, Line, Tlen+1, 42, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {42,Tlen,Ics,Line,43};
yystate(42, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(41, [124|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 40, Tlen);
yystate(41, [101|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 40, Tlen);
yystate(41, [69|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 40, Tlen);
yystate(41, [46|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 40, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 40, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {40,Tlen,Ics,Line,41};
yystate(40, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(39, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line+1, Tlen+1, Action, Alen);
yystate(39, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [45|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 34, Tlen);
yystate(38, [43|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 34, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, 34, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,38};
yystate(37, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(36, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(35, [124|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 16, Tlen);
yystate(35, [101|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 16, Tlen);
yystate(35, [69|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 16, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(49, Ics, Line, Tlen+1, 16, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,35};
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, 38, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,34};
yystate(33, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(32, [61|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 29, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,32};
yystate(31, [124|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, [101|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, [69|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, [46|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,31};
yystate(30, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(29, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(28, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(22, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(22, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,26};
yystate(25, [61|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 22, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,25};
yystate(24, [126|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [125|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [124|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [123|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [94|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [93|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [92|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [91|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [63|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [62|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [61|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [60|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [59|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [58|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [47|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [46|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [45|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [44|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [43|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [42|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [41|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [40|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [38|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [37|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [36|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [35|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [34|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [33|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [32|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [13|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [9|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(28, Ics, Line, Tlen+1, 43, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {43,Tlen,Ics,Line,24};
yystate(23, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line,22};
yystate(21, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(20, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(20, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,20};
yystate(19, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(18, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(17, [61|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 18, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,17};
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 30, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(20, Ics, Line, Tlen+1, 30, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(20, Ics, Line, Tlen+1, 30, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,16};
yystate(15, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(14, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(13, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(12, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(11, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(10, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(9, [61|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 23, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line,9};
yystate(8, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(7, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(6, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(5, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line};
yystate(4, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(3, Ics, Line, Tlen, _, _) ->
    {44,Tlen,Ics,Line};
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(2, [45|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 37, Tlen);
yystate(2, [43|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 37, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(1, Ics, Line, Tlen+1, 37, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line,2};
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(1, Ics, Line, Tlen+1, 37, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(22, Ics, Line, Tlen+1, 37, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line,1};
yystate(0, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(29, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(33, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars, TokenLine);
yyaction(34, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_34(TokenChars, TokenLine);
yyaction(35, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars, TokenLine);
yyaction(36, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_36(TokenChars, TokenLine);
yyaction(37, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_37(TokenChars, TokenLine);
yyaction(38, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_38(TokenChars, TokenLine);
yyaction(39, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_39(TokenChars, TokenLine);
yyaction(40, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_40(TokenChars, TokenLine);
yyaction(41, _, _, _) ->
    yyaction_41();
yyaction(42, _, _, _) ->
    yyaction_42();
yyaction(43, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_43(TokenChars, TokenLine);
yyaction(44, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_44(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("./lexer.xrl", 15).
yyaction_0(TokenChars, TokenLine) ->
     { token, { 'INC', "<span class=\"INC\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_1/2}).
-file("./lexer.xrl", 18).
yyaction_1(TokenChars, TokenLine) ->
     { token, { 'MIN', "<span class=\"MATH\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_2/2}).
-file("./lexer.xrl", 19).
yyaction_2(TokenChars, TokenLine) ->
     { token, { 'CARET', "<span class=\"MATH\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_3/2}).
-file("./lexer.xrl", 20).
yyaction_3(TokenChars, TokenLine) ->
     { token, { 'PS', "<span class=\"MATH\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_4/2}).
-file("./lexer.xrl", 21).
yyaction_4(TokenChars, TokenLine) ->
     { token, { 'AS', "<span class=\"MATH\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_5/2}).
-file("./lexer.xrl", 22).
yyaction_5(TokenChars, TokenLine) ->
     { token, { 'PER', "<span class=\"MATH\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_6/2}).
-file("./lexer.xrl", 23).
yyaction_6(TokenChars, TokenLine) ->
     { token, { 'SLASH', "<span class=\"MATH\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_7/2}).
-file("./lexer.xrl", 26).
yyaction_7(TokenChars, TokenLine) ->
     { token, { 'LP', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_8/2}).
-file("./lexer.xrl", 27).
yyaction_8(TokenChars, TokenLine) ->
     { token, { 'RP', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_9/2}).
-file("./lexer.xrl", 28).
yyaction_9(TokenChars, TokenLine) ->
     { token, { 'LB', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_10/2}).
-file("./lexer.xrl", 29).
yyaction_10(TokenChars, TokenLine) ->
     { token, { 'RB', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_11/2}).
-file("./lexer.xrl", 30).
yyaction_11(TokenChars, TokenLine) ->
     { token, { 'LB', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_12/2}).
-file("./lexer.xrl", 31).
yyaction_12(TokenChars, TokenLine) ->
     { token, { 'RB', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_13/2}).
-file("./lexer.xrl", 32).
yyaction_13(TokenChars, TokenLine) ->
     { token, { 'DP', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_14/2}).
-file("./lexer.xrl", 33).
yyaction_14(TokenChars, TokenLine) ->
     { token, { 'SEMI', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_15/2}).
-file("./lexer.xrl", 34).
yyaction_15(TokenChars, TokenLine) ->
     { token, { 'COMMA', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_16/2}).
-file("./lexer.xrl", 35).
yyaction_16(TokenChars, TokenLine) ->
     { token, { 'DOT', "<span class=\"DIV\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_17/2}).
-file("./lexer.xrl", 38).
yyaction_17(TokenChars, TokenLine) ->
     { token, { 'ASAS', "<span class=\"COMP\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_18/2}).
-file("./lexer.xrl", 39).
yyaction_18(TokenChars, TokenLine) ->
     { token, { 'AS', "<span class=\"COMP\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_19/2}).
-file("./lexer.xrl", 40).
yyaction_19(TokenChars, TokenLine) ->
     { token, { 'LTA', "<span class=\"COMP\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_20/2}).
-file("./lexer.xrl", 41).
yyaction_20(TokenChars, TokenLine) ->
     { token, { 'GTA', "<span class=\"COMP\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_21/2}).
-file("./lexer.xrl", 42).
yyaction_21(TokenChars, TokenLine) ->
     { token, { 'DIFF', "<span class=\"COMP\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_22/2}).
-file("./lexer.xrl", 43).
yyaction_22(TokenChars, TokenLine) ->
     { token, { 'LT', "<span class=\"COMP\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_23/2}).
-file("./lexer.xrl", 44).
yyaction_23(TokenChars, TokenLine) ->
     { token, { 'GT', "<span class=\"COMP\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("./lexer.xrl", 47).
yyaction_24(TokenLine) ->
     { token, { 'WS', "\n<br />", TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("./lexer.xrl", 48).
yyaction_25(TokenLine) ->
     { token, { 'WS', "\r", TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("./lexer.xrl", 49).
yyaction_26(TokenLine) ->
     { token, { 'WS', "\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("./lexer.xrl", 50).
yyaction_27(TokenLine) ->
     { token, { 'WS', "&nbsp;", TokenLine } } .

-compile({inline,yyaction_28/2}).
-file("./lexer.xrl", 53).
yyaction_28(TokenChars, TokenLine) ->
     { token, { 'TILDE', "<span class=\"CARACT\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_29/2}).
-file("./lexer.xrl", 54).
yyaction_29(TokenChars, TokenLine) ->
     { token, { 'EM', "<span class=\"CARACT\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_30/2}).
-file("./lexer.xrl", 55).
yyaction_30(TokenChars, TokenLine) ->
     { token, { 'NS', "<span class=\"CARACT\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_31/2}).
-file("./lexer.xrl", 56).
yyaction_31(TokenChars, TokenLine) ->
     { token, { 'DOLL', "<span class=\"CARACT\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_32/2}).
-file("./lexer.xrl", 57).
yyaction_32(TokenChars, TokenLine) ->
     { token, { 'AMPER', "<span class=\"CARACT\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_33/2}).
-file("./lexer.xrl", 58).
yyaction_33(TokenChars, TokenLine) ->
     { token, { 'US', "<span class=\"CARACT\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_34/2}).
-file("./lexer.xrl", 59).
yyaction_34(TokenChars, TokenLine) ->
     { token, { 'VB', "<span class=\"CARACT\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_35/2}).
-file("./lexer.xrl", 60).
yyaction_35(TokenChars, TokenLine) ->
     { token, { 'BS', "<span class=\"CARACT\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_36/2}).
-file("./lexer.xrl", 61).
yyaction_36(TokenChars, TokenLine) ->
     { token, { 'QM', "<span class=\"CARACT\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_37/2}).
-file("./lexer.xrl", 65).
yyaction_37(TokenChars, TokenLine) ->
     Atom = list_to_atom (TokenChars),
    
     case reserved_word (Atom) of
     true -> { token, { 'RW', "<span class=\"RW\">" ++ TokenChars ++ "</span>", TokenLine } } ;
     false -> diferenciador (Atom, TokenChars, TokenLine)
     end .

-compile({inline,yyaction_38/2}).
-file("./lexer.xrl", 75).
yyaction_38(TokenChars, TokenLine) ->
     { token, { 'FLOAT', "<span class=\"NUMBER2\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_39/2}).
-file("./lexer.xrl", 78).
yyaction_39(TokenChars, TokenLine) ->
     { token, { 'FLOAT', "<span class=\"NUMBER1\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_40/2}).
-file("./lexer.xrl", 80).
yyaction_40(TokenChars, TokenLine) ->
     { token, { 'INTEGER', "<span class=\"NUMBER\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_41/0}).
-file("./lexer.xrl", 83).
yyaction_41() ->
     skip_token .

-compile({inline,yyaction_42/0}).
-file("./lexer.xrl", 84).
yyaction_42() ->
     skip_token .

-compile({inline,yyaction_43/2}).
-file("./lexer.xrl", 88).
yyaction_43(TokenChars, TokenLine) ->
     { token, { 'QM', "<span class=\"STRING\">" ++ TokenChars ++ "</span>", TokenLine } } .

-compile({inline,yyaction_44/2}).
-file("./lexer.xrl", 90).
yyaction_44(TokenChars, TokenLine) ->
     { token, { 'QM', "<span class=\"STRING\">" ++ TokenChars ++ "</span>", TokenLine } } .

-file("/usr/local/Cellar/erlang/23.3/lib/erlang/lib/parsetools-2.2/include/leexinc.hrl", 313).
